### ISSUE TITLE
Dynamically passing content key from model to template

### ISSUE THREAD

**Issue by mikesparr** [krakenjs/makara#36]
I read in #21 that you cannot pass in content key dynamically to a template.  I am curious whether my issue in #35 could be solved by having a list of keys in the model object and the template could evaluate those keys and inject the proper content from the current resource bundle.

**Example Model:**

```
...
        filters: [
            {name_key:'filter.id', hint_key:'filter.hint.id'},
            {name_key:'filter.name', hint_key:'filter.hint.name'},
            {name_key:'filter.title', hint_key:'filter.hint.title'},
            {name_key:'filter.email', hint_key:'filter.hint.email'},
            ...
        ],
...
```

**Example property bundle:**

```
filter.id=ID
filter.hint.id=E.g. '1234'
filter.name=Name
filter.hint.name=E.g. 'Mike' or 'Sally Jones'
filter.title=Title
filter.hint.title=E.g. 'Broker'
filter.email=Email
filter.hint.email=E.g. 'joe@someco.com' or 'someco.com'
```

**On the template perhaps:**

```
...

{#filters}
<a href='#' title='{@pre type="content" key="{hint_key}" /}'>{@pre type="content" key="{name_key}" /}</a>
{/filters}

...
```

I appreciate steer on how best to accomplish #35 and whether this might be possible but I'm missing something.

**Comment by brakon** [comment]
What will be the new design without build-time localization?

**Comment by aredridel** [comment]
Templates will include `@pre` (deprecated), `@message` (backward-compatible) or `@formatMessage` (via formatjs.io project) helpers, and you can plug in a language bundle resolver that will supply bundles of strings. At the moment, that means loading a language-specific `<script>` tag with the actual strings, in addition to the javascript bundle of your app.
