### ISSUE TITLE
Map in a list

### ISSUE THREAD

**Issue by HlodowigRaginwald** [krakenjs/makara#37]
it is possible to put a map in a list ?  

in my properties file :
```
index.map[0].aa=foo
index.map[1].aa=bar
```

In this case the bundle of index return this :
```
{ map: [ 'foo', 'bar ] }
```

But would like something like that :
```
{ map: [{aa : 'foo'},{aa:  'bar'}]}
```

It is possible ?

I use makara with kraken-js.

Thanks !

**Comment by aredridel** [comment]
Feel free to reopen if you can show some context where this is useful in the context of localization, not just generic data structures.
