### ISSUE TITLE
Sharing Content

### ISSUE THREAD

**Issue by nomanurrehman** [krakenjs/makara#50]
From the docs:

"If you have content you want to share across pages, then you should factor out use of that content into a separate partial and use that partial to achieve content sharing."

Can you please explain this a bit ?

For example, if I have messages and want them to be available to every template, how do I do that ?

**Comment by shaoner** [comment]
Hi,

@aredridel, just wondering if the content-sharing feature is still considered for 2.0?
I've been using partials to achieve that until now, but having a lot of partials (requiring two files) mixed up with `@pre` tags is a bit complicated (to read & maintain).

**Comment by aredridel** [comment]
Yes indeed! 

There's a new helper -- `dust-usecontent-helper`, which provides a `{@useContent bundle="filename"} ...  {/@useContent}` block you can use, which will let you select content out of a specific bundle.

**Comment by shaoner** [comment]
Oh, awesome!
Thanks!

**Comment by aredridel** [comment]
Sure thing! You probably want to use it via `dust-makara-helpers` -- the raw setup for `dust-usecontent-helper` means you have to supply a content loading function.

**Comment by shaoner** [comment]
Well yes thank you!
I suppose it replaces `engine-munger/node_modules/localizr` from `kraken@1.x` to deal with `@pre` tags on the fly, so I'll wait for `kraken@2.x` to be ready since `dust-makara-helpers` depends on another dust major version.

**Comment by aredridel** [comment]
It's actually independent of kraken-js 2.0.0. makara works with it, but kraken 1.0 doesn't care what templating you use.

**Comment by aredridel** [comment]
(and yes, everything new depends on dust ^2.7.1. The interfaces changed.)

**Comment by shaoner** [comment]
Ok cool, I was not aware I could replace `engine-munger` by `makara`.
I was just refering the previous version of `engine-munger` depending on `dust` <= 2.0.0

**Comment by aredridel** [comment]
Yep! Still writing docs on how to migrate -- it's a big re-arrangement, since the way it was factored before was not quite the right divisions.

**Comment by shaoner** [comment]
I've just migrated, and it works pretty well!
Apart from the configuration aspect, it seems that a `file.properties` is now required for any template file (which differs from localizr).

**Comment by aredridel** [comment]
Awesome! Glad to hear that it's working for you.

There were edge cases prior where those files were required, but yes, you could generally work without them -- I made the decision to require them, but I'd be open to relaxing that in future. Open an issue if the below doesn't handle your use case.

You can avoid this by disabling `autoloadTemplateContent` in `dust-makara-helpers`. I've not documented it yet, but it requires you use `{@useContent}` for all content loads, there will be no automatic loading of any property bundles.

**Comment by shaoner** [comment]
Yep, I'm very happy with the `useContent` helper so far! I really missed it (especially for error messages in my case (it's pretty convenient to group them in a single bundle)). 
About the required `file.properties`, it can just be a bit confusing because usually you think about the corresponding properties file only when you need to. Now, when adding a partial that doesn't need any translation you also need to add an empty file for each locale/*/*. But anyway, it can easily be dealt with.
Thanks again for your help and your great work.

**Comment by kurdin** [comment]
@aredridel can you please explain how to disable `autoloadTemplateContent` this is an odd behavior to require creating empty `file.properties` for each template and partials you use, even if there is no  translations in them.

**Comment by grawk** [comment]
@kurdin this has been documented here:
https://github.com/krakenjs/dust-makara-helpers#options

As a practical matter, if you are configuring this in the `config.json` of a typical kraken app, it would look like this:

``` js
"view engines": {
        "dust": {
            "module": "makara",
            "renderer": {
                "method": "dust",
                "arguments": [
                    { "cache": true, "helpers": "config:dust.helpers" }
                ]
            }
        }
    },

    "dust": {
        "helpers": [

            {
                "name": "dust-makara-helpers",
                "arguments": { "autoloadTemplateContent": false }
            },
            "dustjs-helpers",
            "./public/js/lib/dusty-helper"
        ]
    },
```
