### ISSUE TITLE
Plan for makara deprecation

### ISSUE THREAD

**Issue by grawk** [krakenjs/makara#57]
Would be good to have a scheduled rollout of makara deprecation possibly including:
* documentation for making the switch, with a reference to doc from makara README
* deprecation warning from makara
* timeline/milestones

**Comment by tkambler** [comment]
Deprecation? What deprecation? krakenjs.com references Makara. Could someone please provide a clear explanation of how new projects based on Kraken should be implementing localization?

**Comment by aredridel** [comment]
kraken 1.0 projects use localizr, engine-munger, adaro, bundalo and grunt-localizr. They were extracted from makara for the 1.0 release. Use those, with dust < 2.7

I'm working on new components -- a simplified engine-munger, reworked adaro to work with dust 2.7 -- they will be bundled into a kraken-friendly configuration as a new release of makara

**Comment by aredridel** [comment]
Makara 2.0.0 has been released!
