### ISSUE TITLE
dust helpers documentation is wrong

### ISSUE THREAD

**Issue by jknight12882** [krakenjs/makara#68]
On the blog, you have this 

```
"dust": {
    "helpers": [
        {
            "module": "dust-makara-helpers",
            "arguments": [ { "autoloadTemplateContent": false } ]
        }
    ]
}
```

It actually needs to be this

```
"dust": {
    "helpers": [{
        "name": "dust-makara-helpers",
        "arguments": { "autoloadTemplateContent": false }
    }]
},
```

**Comment by grawk** [comment]
True, that is the syntax I'm using locally. @jknight12882 do you want to PR that change into the blog?
https://github.com/krakenjs/krakenjs.github.io/blob/master/_posts/2015-07-09-upgrading-makara.md
