### ISSUE TITLE
Problem with format path

### ISSUE THREAD

**Issue by sonnyCZE** [krakenjs/makara#75]
Hi,
I have problem with convert a locale to a path fragment if the locale has only 2 chars (ex. cs (Czech)). It can't find the properties files in path ./locales/cs/index.properties (throw error Failed to lookup view). The path is correct.

With locale en_US everything works great.

Is this a bug?

So I would like to change i18n.formatPath but I can't to figure out how to do this in krakenjs. Can you help me, please?

**Comment by aredridel** [comment]
`formatPath` is a plain function -- you can put that function in a module then use the `require:` shortstop handler to load it.

Are you parsing locales without a country?

**Comment by sonnyCZE** [comment]
I overlooked the `require:` shortstop handler. Thanks for that tip. Now it working as I need.

I am parsing http header Accept-Language which contains (in some cases) locales without a country.

Thanks again for quick response.

**Comment by aredridel** [comment]
Glad to help!
