### ISSUE TITLE
Makara 2 and Dust @provide helper

### ISSUE THREAD

**Issue by connesc** [krakenjs/makara#76]
I recently upgraded a Kraken project to Makara 2, and I discovered that [the combination of `mode="paired"` and `@provide`](https://github.com/krakenjs/makara/blob/v2.x/ADVANCED.md) does not work anymore.

I took me a while to figure out that `@provide` (from [dustmotes-provide](https://github.com/rragan/dust-motes/tree/master/src/helpers/data/provide)) is not able to consume the output of `@message`. I think that this breaking change should be mentioned somewhere (at least in [this page](https://github.com/krakenjs/makara/blob/v2.x/ADVANCED.md)).

If anyone is interested, I solved the problem by writing my own `@provide` helper: [dust-provide-helper](https://github.com/unitag/dust-provide-helper). It is not perfect, but it can be used as a drop-in replacement for [dustmotes-provide](https://github.com/rragan/dust-motes/tree/master/src/helpers/data/provide) with Makara 2.

**Comment by grawk** [comment]
Sorry for the delay. I will be looking into this.

**Comment by grawk** [comment]
Hi @connesc I'm investigating this now. I see that your new helper code does work in `paired` mode while the original `@provide` helper code does not. I've forked the `@provide` helper (and other `dustmotes` helpers) into the krakenjs org (as https://github.com/krakenjs/festucam) in order that we can keep them up to date. The original author has retired and I think this is the best way to support them going forward. Would you mind opening a PR against festucam with your changes? If you're not actively working on dust anymore, I'm happy to open the PR myself and add you as a "contributor" in package.json. Let me know.

**Comment by connesc** [comment]
Hi @grawk, and thanks for this follow up.
Your PR looks good to me, well done!
