### ISSUE TITLE
Locale specific templates

### ISSUE THREAD

**Issue by Noyabronok** [krakenjs/makara#81]
Let's say I would like to make a separate template file per locale in a Kraken application.  Something like this:

```
/templates
  /US   -??
    myview.dust
  /GB   -??
    myview.dust
```

And properties structure like

```
/US
  /en
     myview.properties
/GB
  /en
     myview.properties
```

Do I need to specify a custom Makara `formatPath` function, or should there be some other approach?

**Comment by grawk** [comment]
I'm pretty sure you don't need to customize `formatPath`. That is only responsible for the filesystem lookup of properties files based on the bcp47-style locale object.

I'm working through an example to see if I can give you a good recommendation for your use case.

**Comment by grawk** [comment]
What do you think about using dynamic partial naming as described here: https://github.com/linkedin/dustjs/wiki/Dust-little-less-know-language-constructs#dynamic-partials

Then you'd have something like this:

```
/templates
    index.dust
    /partials
        myview-US.dust
        myview-GB.dust
```

And properties structure:

```
/locales
    /GB
        /en
            myview-GB.properties
    /US
        /en
            myview-GB.properties
            myview-US.properties
```

You would want to have all possible properties files defined in your default locale (en-US) and then override properties files per applicable locale.

**Comment by Noyabronok** [comment]
Thanks Matt.  

The application already implements dynamic partials exactly as you describe.  However, I don't understand why we need/want a `/US/en/myview-GB.properties` file when the path clearly states that the country is US.  I am not crazy about having the country code as part of the filenames, especially in properties files.  

I think it would be cleaner if there would be a single property file per locale, and that the property filename not specify any additional country codes.  For dust files the country code is needed to differentiate the template, but I think it's better to place the code in the folder path instead of filename.   Both ideas are in my original post example.

Thank you!

**Comment by grawk** [comment]
If you're already dynamically selecting partials from the directory structure you've outlined, then you should just be able to use the `useContent` helper to select the appropriate properties file.

E.g.

/templates/US/myview.dust

```
{@useContent bundle="myview.properties"}

...

{/useContent}
```

You will have to add the argument to `dust-makara-helpers` to not infer the properties name/location from the template name/location:

config.json (typical)

```
"dust": {
        "helpers": [
            {
                "name": "dust-makara-helpers",
                "arguments": { "autoloadTemplateContent": false }
            }
        ]
    },
```
