### ISSUE TITLE
Build task on windows fails due to OS path separator issue

### ISSUE THREAD

**Issue by msanders70** [krakenjs/makara#82]
The grunt-makara-amdify 1.0.1 uses the makara-builder 1.0.0 and in makara-builder/index.js I can see:

```
    var locales = paths.map(function (p) {
        var m = /(.*)\/(.*)/.exec(path.relative(localeRoot, p));
        return m[2] + '-' + m[1];
    });
```

localeRoot="...\locales" and p="...locales/DE/de"

The path.relative() call transforms p into windows style and returns "DE\de".
The reg ex evaluation returns null because of the hardcoded linux path sep.
The following line gives of course "Fatal error: Cannot read property '2' of null".

Any hint for a workaround? Beside "use linux" ... ;-)

**Comment by grawk** [comment]
Hi @msanders70. Thanks for raising this issue. I think we should fix this in the appropriate module. Would you mind re-filing this against makara-builder?

**Comment by msanders70** [comment]
Done: https://github.com/krakenjs/makara-builder/issues/1

**Comment by grawk** [comment]
Thanks. I'm going to close this now and we can finish this off on your new issue.

**Comment by msanders70** [comment]
Thanks a lot!
