### ISSUE TITLE
is there a concept of fallback at the level of the Country

### ISSUE THREAD

**Issue by lwelti** [krakenjs/makara#83]
so, let's say that you support GB (UK) but you only support one language (en) but for some reason a user has french in the accept-language header and country=GB, so i don't want it to fallback to fr-FR, i want it to fallback to en-GB, is that possible?

**Comment by lwelti** [comment]
in other words, a way to configure the fallback but at the level of the country.

**Comment by aredridel** [comment]
You can provide your own locale resolution rules, yes. Make your own middleware that makes sure that `req.locale` is set to an appropriate value.

However, please be careful doing just that: there is a tension between showing the user content localized for the legalities or marketing in their country, but in a language they do not understand, versus language they understand for another market. Choose these fallbacks wisely and understand your use-case!

**Comment by grawk** [comment]
answered
