### ISSUE TITLE
Question: what are the various ways to manually set the expressjs-res's locale

### ISSUE THREAD

**Issue by suryagh** [krakenjs/makara#85]
(x-post from engine-munger)

I'm using makara in a kraken (yo generated) application. Presently looking for some documentation to find the right approach to manually set the i18n of the express.js http `response` object. So that right `.properties` file gets picked-up based on the **business logic**.

Below is one method I found by trail and error, where the GB version of properties file gets picked-up correctly even though my browser has `Accept-Language` for US locale.

 `res.render('index', { name: 'index', locale: 'en_GB'});`

However, not certain if this  is the right way, or could there be some situation that I'm unaware of during the run time where (user/browser settings, or, ..?) the above approach will get  overridden and an incorrect `.properties` file will get picked up?
### Question:
1. Can someone please point me to any documentation which explains how the locale can be manually set from a kraken-node-MVC-controller? 
2. If there are various ways, then which approach gets the highest priority?

**Comment by grawk** [comment]
This is what I do:
https://github.com/grawk/try18n/blob/master/lib/locale.js#L5-L8

``` js
module.exports = function () {
    return function (req, res, next) {
        res.locals.locale = {
            country: req.query.country || 'US',
            language: req.query.language || 'en'
        };
        next();
    };
};
```

This is the recommended approach.

**Comment by suryagh** [comment]
@grawk the `model.locale` seems to have the higher priority. For e.g., with the below code, the GB `.properties` files are getting picked.

```
res.locals.locale = {
            country:  'US',
            language:   'en'
        };
res.render('index', { name: 'index', locale: 'en_GB'});
```

Should this be a bug?

**Comment by grawk** [comment]
No I don't think it's a bug. If you look where the locale is being pulled from the context, "locale" does come first:
https://github.com/krakenjs/dust-makara-helpers/blob/v4.x/index.js#L82-L83

``` javascript
/* excerpt from above */
return stringLocale(ctx.get('contentLocale') || ctx.get('contentLocality') ||
        ctx.get('locale') || ctx.get('locality') || {});
```

**Comment by suryagh** [comment]
@grawk thank you.
